server:
  port: 8080
  servlet:
    session:
      timeout: PT24H    #session?????24h

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references : true
  datasource:
    username: root
    password: 20000209
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.qq.com    #邮箱服务器地址
    username: 1067865757@qq.com   #邮箱账号
    password: ggwwhhytbvuhbecd      #邮箱授权码
    default-encoding: utf-8    #默认编码
    properties:
      mail:
        stmp:
          ssl:
            enable=true:


# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 微信开放平台 appid()



