server:
  port: 8080
  servlet:
    session:
      timeout: PT24H    #session?????24h

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update




